// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdSQzl_TrbmMUXgbhrcHI3cEtganTJukE',
    appId: '1:452631860879:web:0424547f311101863302fa',
    messagingSenderId: '452631860879',
    projectId: 'assignment-tracker-9ad32',
    authDomain: 'assignment-tracker-9ad32.firebaseapp.com',
    storageBucket: 'assignment-tracker-9ad32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkijABxYbv-PrCxk7jm0G9xRRIvX170KA',
    appId: '1:452631860879:android:4fe4a7b9d1eaf5243302fa',
    messagingSenderId: '452631860879',
    projectId: 'assignment-tracker-9ad32',
    storageBucket: 'assignment-tracker-9ad32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLnZSQ-w9y02ZdTJYkMkx_guiH-Q8ZBzI',
    appId: '1:452631860879:ios:b1d98bc1fb98c3fb3302fa',
    messagingSenderId: '452631860879',
    projectId: 'assignment-tracker-9ad32',
    storageBucket: 'assignment-tracker-9ad32.appspot.com',
    iosBundleId: 'com.example.applicationsTracker',
  );
}
